//
//  MessagesViewController.swift
//  MessagesExtension
//
//  Created by Drew Lanning on 2/3/17.
//  Copyright © 2017 Drew Lanning. All rights reserved.
//

import UIKit
import Messages

class MessagesViewController: MSMessagesAppViewController {
  
  override func viewDidLoad() {
    super.viewDidLoad()
    // Do any additional setup after loading the view.
  }
  
  private func presentVC(for conversation: MSConversation, with presentationStyle: MSMessagesAppPresentationStyle) {
    
    var controller: UIViewController
    
    if presentationStyle == .compact {
      controller = instantiateCompactVC()
    } else {
      controller = instantiateExpandedVC(forConversation: conversation)
    }
    
    for child in childViewControllers {
      child.willMove(toParentViewController: nil)
      child.view.removeFromSuperview()
      child.removeFromParentViewController()
    }
    
    addChildViewController(controller)
    
    controller.view.frame = view.bounds
    controller.view.translatesAutoresizingMaskIntoConstraints = false
    view.addSubview(controller.view)
    
    controller.view.leftAnchor.constraint(equalTo: view.leftAnchor).isActive = true
    controller.view.rightAnchor.constraint(equalTo: view.rightAnchor).isActive = true
    controller.view.topAnchor.constraint(equalTo: view.topAnchor).isActive = true
    controller.view.bottomAnchor.constraint(equalTo: view.bottomAnchor).isActive = true
    
    controller.didMove(toParentViewController: self)
  }
  
  private func instantiateCompactVC() -> UIViewController {
    guard let compactVC = storyboard?.instantiateViewController(withIdentifier: "CompactVC") as? CompactVC else {
      fatalError("Can't make a CompactVC")
    }
    compactVC.delegate = self
    //    compactVC.newGameDelegate = self
    //    compactVC.soundPlayer = soundPlayer
    return compactVC
  }
  
  private func instantiateExpandedVC(forConversation conversation: MSConversation) -> UIViewController {
    guard let vc = storyboard?.instantiateViewController(withIdentifier: "GameVC") as? GameVC else {
      fatalError("VC not found.")
    }
    
    if let message = conversation.selectedMessage {
      vc.message = message
    }
    
    vc.composeDelegate = self
    
//    if let game = startingGame {
//      vc.game = game
//    } else {
//      let wordList = WordsAPI()
//      self.startingGame = Game(withMessage: nil)
//      startingGame?.setCurrentWord(to: wordList.fetchRandomWord()!)
//      vc.game = startingGame!
//    }
//    vc.soundPlayer = soundPlayer
    vc.conversation = conversation
    return vc
  }
  
  
  // MARK: - Conversation Handling
  
  override func willBecomeActive(with conversation: MSConversation) {
    presentVC(for: conversation, with: presentationStyle)
  }
  
  override func didResignActive(with conversation: MSConversation) {
    // Called when the extension is about to move from the active to inactive state.
    // This will happen when the user dissmises the extension, changes to a different
    // conversation or quits Messages.
    
    // Use this method to release shared resources, save user data, invalidate timers,
    // and store enough state information to restore your extension to its current state
    // in case it is terminated later.
  }
  
  override func didReceive(_ message: MSMessage, conversation: MSConversation) {
    // Called when a message arrives that was generated by another instance of this
    // extension on a remote device.
    
    // Use this method to trigger UI updates in response to the message.
  }
  
  override func didStartSending(_ message: MSMessage, conversation: MSConversation) {
    // Called when the user taps the send button.
  }
  
  override func didCancelSending(_ message: MSMessage, conversation: MSConversation) {
    // Called when the user deletes the message without sending it.
    
    // Use this to clean up state related to the deleted message.
  }
  
  override func willTransition(to presentationStyle: MSMessagesAppPresentationStyle) {
    guard let conversation = activeConversation else {
      fatalError("No active conversation or something")
    }
    presentVC(for: conversation, with: presentationStyle)
  }
  
  override func didTransition(to presentationStyle: MSMessagesAppPresentationStyle) {
    // Called after the extension transitions to a new presentation style.
    
    // Use this method to finalize any behaviors associated with the change in presentation style.
  }
  
  override func didSelect(_ message: MSMessage, conversation: MSConversation) {
    guard let conversation = activeConversation else {
      fatalError("No active conversation or something")
    }
    presentVC(for: conversation, with: presentationStyle)
  }
  
}

extension MessagesViewController: ExpandViewDelegate {
  func expand(toPresentationStyle presentationStyle: MSMessagesAppPresentationStyle) {
    requestPresentationStyle(presentationStyle)
  }
  func getPresentationStyle() -> MSMessagesAppPresentationStyle {
    return self.presentationStyle
  }
}

extension MessagesViewController: ComposeMessageDelegate {
  func compose(fromGame game: ChicagoModel) {
    let convo = activeConversation ?? MSConversation()
    let session = convo.selectedMessage?.session ?? MSSession()
    
    let layout = MSMessageTemplateLayout()
    layout.caption = "$\(convo.localParticipantIdentifier)"
    
    let message = MSMessage(session: session)
    message.layout = layout
    
    var components = URLComponents()
    let potSize = URLQueryItem(name: GameItemNames.potSize.rawValue, value: "\(game.potOfChips)")
    let phase = URLQueryItem(name: GameItemNames.phase.rawValue, value: "\(game.currentPhase.rawValue)")
    let numberOfPlayers = URLQueryItem(name: GameItemNames.numberOfPlayers.rawValue, value: "\(game.players.count)")
    components.queryItems = [potSize, phase, numberOfPlayers]
    for (index, player) in game.players.enumerated() {
      let playerID = URLQueryItem(name: PlayerItemNames.playerID.rawValue + "\(index)", value: player.playerID)
      components.queryItems?.append(playerID)
      let playerScore = URLQueryItem(name: PlayerItemNames.score.rawValue + "\(index)", value: "\(player.score)")
      components.queryItems?.append(playerScore)
      let playerChips = URLQueryItem(name: PlayerItemNames.chips.rawValue + "\(index)", value: "\(player.chips)")
      components.queryItems?.append(playerChips)
      let playerRollLimit = URLQueryItem(name: PlayerItemNames.rollLimit.rawValue + "\(index)", value: "\(player.rollLimit)")
      components.queryItems?.append(playerRollLimit)
    }
    
    message.summaryText = "$\(convo.localParticipantIdentifier)"
    
    message.url = components.url
    
    convo.insert(message) { (error) in
      guard error == nil else {
        fatalError()
      }
    }
    
    dismiss()
  }
}
